name: Run Magic Match

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet run --project ./MagicMatch/MagicMatch.csproj --configuration Release --no-build
        env:
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          TINDER_AUTH_TOKEN: ${{ secrets.TINDER_AUTH_TOKEN }}
          TINDER_PERSISTENT_DEVICE_ID: ${{ secrets.TINDER_PERSISTENT_DEVICE_ID }}
          TINDER_MESSAGE: ${{ vars.TINDER_MESSAGE }}
          TINDER_MIN_AGE: ${{ vars.TINDER_MIN_AGE }}
          TINDER_MAX_AGE: ${{ vars.TINDER_MAX_AGE }}
          TINDER_MAX_DISTANCE_KM: ${{ vars.TINDER_MAX_DISTANCE_KM }}
          TINDER_MIN_PHOTOS: ${{ vars.TINDER_MIN_PHOTOS }}
          TINDER_MAX_ERRORS: ${{ vars.TINDER_MAX_ERRORS }}
          TINDER_BIO_EXCLUDE_KEYWORDS: ${{ vars.TINDER_BIO_EXCLUDE_KEYWORDS }}
          TINDER_DELAY_RECS_MIN_MS: ${{ vars.TINDER_DELAY_RECS_MIN_MS }}
          TINDER_DELAY_RECS_MAX_MS: ${{ vars.TINDER_DELAY_RECS_MAX_MS }}
          TINDER_DELAY_MESSAGES_MIN_MS: ${{ vars.TINDER_DELAY_MESSAGES_MIN_MS }}
          TINDER_DELAY_MESSAGES_MAX_MS: ${{ vars.TINDER_DELAY_MESSAGES_MAX_MS }}
          TINDER_DELAY_MATCHES_MIN_MS: ${{ vars.TINDER_DELAY_MATCHES_MIN_MS }}
          TINDER_DELAY_MATCHES_MAX_MS: ${{ vars.TINDER_DELAY_MATCHES_MAX_MS }}
          TINDER_DELAY_BETWEEN_EXECUTIONS_MIN_MINUTES: ${{ vars.TINDER_DELAY_BETWEEN_EXECUTIONS_MIN_MINUTES }}
          TINDER_DELAY_BETWEEN_EXECUTIONS_MAX_MINUTES: ${{ vars.TINDER_DELAY_BETWEEN_EXECUTIONS_MAX_MINUTES }}